"""schema inicial

Revision ID: 1dcb7aeb1199
Revises: 
Create Date: 2026-06-22 01:23:45.757874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcb7aeb1199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'CONFIRM', 'CANCEL', 'ASSIGN', 'PAYMENT', 'PRICING_OVERRIDE', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'admin_audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'admin_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'admin_audit_logs', ['user_id'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_admin_users_email', 'admin_users', ['email'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('one_way_price_cents', sa.Integer(), nullable=False),
    sa.Column('round_trip_price_cents', sa.Integer(), nullable=False),
    sa.Column('sprinter_one_way_price_cents', sa.Integer(), nullable=False),
    sa.Column('sprinter_round_trip_price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_areas_is_active', 'areas', ['is_active'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drivers_is_active', 'drivers', ['is_active'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotels_is_active', 'hotels', ['is_active'], unique=False)
    op.create_index('ix_hotels_zone', 'hotels', ['zone'], unique=False)
    op.create_table('pricing_extras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('code', sa.Enum('INCLUDED_BASIC_KIT', 'GROCERY_STOP', 'EXTRA_STOP', 'BABY_SEAT', 'BOOSTER', 'MEET_GREET', 'SPECIAL_ASSISTANCE', 'OVERSIZE_LUGGAGE', 'WAIT_TIME', 'LATE_NIGHT', 'EARLY_MORNING', 'CHAMPAGNE', 'CHAMPAGNE_UPGRADE', 'LUXURY_WELCOME', 'ROMANTIC_KIT', 'BIRTHDAY_KIT', 'DELUXE_ARRIVAL_KIT', name='extracode'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('label_es', sa.String(length=255), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('pricing_mode', sa.Enum('PER_BOOKING', 'PER_STOP', 'PER_SEAT', 'PER_HOUR', name='pricingmode'), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_extras_active', 'pricing_extras', ['active'], unique=False)
    op.create_index('ix_pricing_extras_code', 'pricing_extras', ['code'], unique=False)
    op.create_index('ix_pricing_extras_included', 'pricing_extras', ['included'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('service_type', sa.Enum('TRANSFER', 'ACTIVITY', 'COMBO', name='servicetype'), nullable=False),
    sa.Column('trip_type', sa.Enum('ONE_WAY', 'ROUND_TRIP', name='triptype'), nullable=False),
    sa.Column('zone_from', sa.String(length=100), nullable=False),
    sa.Column('zone_to', sa.String(length=100), nullable=False),
    sa.Column('vehicle_class', sa.Enum('SUV', 'SUBURBAN', 'SPRINTER', 'VAN', 'SEDAN', 'LUXURY', name='vehicleclass'), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('passengers_min', sa.Integer(), nullable=True),
    sa.Column('passengers_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_rules_active_type_trip', 'pricing_rules', ['active', 'service_type', 'trip_type'], unique=False)
    op.create_index('ix_pricing_rules_vehicle_class', 'pricing_rules', ['vehicle_class'], unique=False)
    op.create_index('ix_pricing_rules_zones', 'pricing_rules', ['zone_from', 'zone_to'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_is_active', 'vehicles', ['is_active'], unique=False)
    op.create_index('ix_vehicles_license_plate', 'vehicles', ['license_plate'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('TRANSPORTATION', 'ACTIVITY', 'COMBO', 'CRAZY_COMBO', name='booking_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_PAYMENT', 'PAID', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'OFFLINE_HOLD', name='booking_status_enum'), nullable=False),
    sa.Column('source', sa.Enum('WEBSITE', 'PHONE', 'WHATSAPP', 'ADMIN', 'AI_CHAT', name='booking_source_enum'), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False, comment='Fecha del servicio'),
    sa.Column('booking_time', sa.String(length=5), nullable=True, comment='Hora del servicio (HH:MM)'),
    sa.Column('pickup_time', sa.String(length=5), nullable=True, comment='Hora exacta de pickup (HH:MM)'),
    sa.Column('pickup_location', sa.Text(), nullable=True),
    sa.Column('dropoff_location', sa.Text(), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('arrival_time', sa.String(length=5), nullable=True),
    sa.Column('arrival_airline', sa.String(length=100), nullable=True),
    sa.Column('departure_flight_number', sa.String(length=20), nullable=True),
    sa.Column('departure_time', sa.String(length=5), nullable=True),
    sa.Column('departure_airline', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False, comment='Total en centavos (USD)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amount', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('trip_type', sa.String(length=50), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('confirmation_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_code')
    )
    op.create_index('ix_bookings_booking_date', 'bookings', ['booking_date'], unique=False)
    op.create_index('ix_bookings_confirmation_code', 'bookings', ['confirmation_code'], unique=False)
    op.create_index('ix_bookings_created_at', 'bookings', ['created_at'], unique=False)
    op.create_index('ix_bookings_customer_id', 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_type_status', 'bookings', ['type', 'status'], unique=False)
    op.create_table('client_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ON_HOLD', 'SETTLED', 'CLOSED', name='clientaccountstatus'), nullable=False),
    sa.Column('credit_limit_cents', sa.Integer(), nullable=True),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_accounts_created_at', 'client_accounts', ['created_at'], unique=False)
    op.create_index('ix_client_accounts_customer_id', 'client_accounts', ['customer_id'], unique=False)
    op.create_index('ix_client_accounts_status', 'client_accounts', ['status'], unique=False)
    op.create_table('account_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PAID', 'VOID', name='accountchargestatus'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_charges_account_status', 'account_charges', ['account_id', 'status'], unique=False)
    op.create_index('ix_account_charges_booking_id', 'account_charges', ['booking_id'], unique=False)
    op.create_index('ix_account_charges_service_date', 'account_charges', ['service_date'], unique=False)
    op.create_table('account_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'CARD', 'MANUAL', name='accountpaymentmethod'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['client_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_payments_account_id', 'account_payments', ['account_id'], unique=False)
    op.create_index('ix_account_payments_received_at', 'account_payments', ['received_at'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('user_message', sa.String(length=2000), nullable=False),
    sa.Column('assistant_reply', sa.String(length=4000), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('raw_transcript', sa.String(length=10000), nullable=True),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('audio_file_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('next_action', sa.String(length=50), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_conversations_booking_id', 'ai_conversations', ['booking_id'], unique=False)
    op.create_index('ix_ai_conversations_created_at', 'ai_conversations', ['created_at'], unique=False)
    op.create_index('ix_ai_conversations_session_id', 'ai_conversations', ['session_id'], unique=False)
    op.create_table('booking_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DRIVER', 'VEHICLE', name='bookingassignmenttype'), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_assignments_booking_id', 'booking_assignments', ['booking_id'], unique=False)
    op.create_index('ix_booking_assignments_driver_id', 'booking_assignments', ['driver_id'], unique=False)
    op.create_index('ix_booking_assignments_vehicle_id', 'booking_assignments', ['vehicle_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('TRANSPORTATION', 'ACTIVITY', 'ADDON', 'PARK_ENTRANCE', 'COMBO', 'CRAZY_COMBO', name='bookingitemtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='Precio unitario en centavos'),
    sa.Column('total_price', sa.Integer(), nullable=False, comment='Precio total en centavos'),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_items_booking_id', 'booking_items', ['booking_id'], unique=False)
    op.create_index('ix_booking_items_type', 'booking_items', ['type'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER_CONFIRMATION', 'COMPANY_NOTIFICATION', 'ADMIN_RESEND', 'BOOKING_RECEIVED', 'MANUAL_CONFIRMED', 'CANCELLED', name='emailtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='emailstatus'), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('bcc', sa.String(length=255), nullable=True),
    sa.Column('from', sa.String(length=255), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_logs_booking_id', 'email_logs', ['booking_id'], unique=False)
    op.create_index('ix_email_logs_created_at', 'email_logs', ['created_at'], unique=False)
    op.create_index('ix_email_logs_sent_at', 'email_logs', ['sent_at'], unique=False)
    op.create_index('ix_email_logs_type_status', 'email_logs', ['type', 'status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'CASH', 'BANK_TRANSFER', 'MANUAL', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('capture_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Monto en centavos'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_provider_status', 'payments', ['provider', 'status'], unique=False)
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_table('pricing_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('original_amount', sa.Integer(), nullable=False),
    sa.Column('override_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_overrides_booking_id', 'pricing_overrides', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_overrides_booking_id', table_name='pricing_overrides')
    op.drop_table('pricing_overrides')
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_index('ix_payments_provider_status', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_email_logs_type_status', table_name='email_logs')
    op.drop_index('ix_email_logs_sent_at', table_name='email_logs')
    op.drop_index('ix_email_logs_created_at', table_name='email_logs')
    op.drop_index('ix_email_logs_booking_id', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index('ix_booking_items_type', table_name='booking_items')
    op.drop_index('ix_booking_items_booking_id', table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index('ix_booking_assignments_vehicle_id', table_name='booking_assignments')
    op.drop_index('ix_booking_assignments_driver_id', table_name='booking_assignments')
    op.drop_index('ix_booking_assignments_booking_id', table_name='booking_assignments')
    op.drop_table('booking_assignments')
    op.drop_index('ix_ai_conversations_session_id', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_created_at', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_booking_id', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('ix_account_payments_received_at', table_name='account_payments')
    op.drop_index('ix_account_payments_account_id', table_name='account_payments')
    op.drop_table('account_payments')
    op.drop_index('ix_account_charges_service_date', table_name='account_charges')
    op.drop_index('ix_account_charges_booking_id', table_name='account_charges')
    op.drop_index('ix_account_charges_account_status', table_name='account_charges')
    op.drop_table('account_charges')
    op.drop_index('ix_client_accounts_status', table_name='client_accounts')
    op.drop_index('ix_client_accounts_customer_id', table_name='client_accounts')
    op.drop_index('ix_client_accounts_created_at', table_name='client_accounts')
    op.drop_table('client_accounts')
    op.drop_index('ix_bookings_type_status', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_customer_id', table_name='bookings')
    op.drop_index('ix_bookings_created_at', table_name='bookings')
    op.drop_index('ix_bookings_confirmation_code', table_name='bookings')
    op.drop_index('ix_bookings_booking_date', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_vehicles_license_plate', table_name='vehicles')
    op.drop_index('ix_vehicles_is_active', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_pricing_rules_zones', table_name='pricing_rules')
    op.drop_index('ix_pricing_rules_vehicle_class', table_name='pricing_rules')
    op.drop_index('ix_pricing_rules_active_type_trip', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index('ix_pricing_extras_included', table_name='pricing_extras')
    op.drop_index('ix_pricing_extras_code', table_name='pricing_extras')
    op.drop_index('ix_pricing_extras_active', table_name='pricing_extras')
    op.drop_table('pricing_extras')
    op.drop_index('ix_hotels_zone', table_name='hotels')
    op.drop_index('ix_hotels_is_active', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index('ix_drivers_is_active', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_areas_is_active', table_name='areas')
    op.drop_table('areas')
    op.drop_index('ix_admin_users_email', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('ix_audit_logs_user_id', table_name='admin_audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='admin_audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='admin_audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
