"""admin_tasks

Revision ID: 55e1faff1097
Revises: 1dcb7aeb1199
Create Date: 2026-06-23 15:42:38.108826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e1faff1097'
down_revision: Union[str, Sequence[str], None] = '1dcb7aeb1199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('categoria', sa.Enum('SERVICIO_VEHICULO', 'OPERACION', 'ADMIN', 'OTRO', name='admintaskcategory'), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'COMPLETADA', 'CANCELADA', name='admintaskstatus'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_tasks_fecha', 'admin_tasks', ['fecha'], unique=False)
    op.create_index('ix_admin_tasks_status', 'admin_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_tasks_status', table_name='admin_tasks')
    op.drop_index('ix_admin_tasks_fecha', table_name='admin_tasks')
    op.drop_table('admin_tasks')
    # ### end Alembic commands ###
